Update pkcs11_interface_stubs to be compatible with CBMC 5.45+
FreeRTOS/corePKCS11 pull request #149
Opened 2022-02-15 22:53 UTC by paulbartell

2022-02-15 23:15 UTC, ravibhagavandas approved these changes

2022-02-15 23:18 UTC, ravibhagavandas requested changes
Seems test are failing with missing `memcpy` definition?

2022-02-16 00:03 UTC, paulbartell commented
> Seems test are failing with missing `memcpy` definition?

Added string.h include in [0348870](https://github.com/FreeRTOS/corePKCS11/commit/0348870302691a1ef0a5c627f56ca0b3586d1114).

I'm guessing it's some kind of compatibility difference between gcc and clang, since this built locally on MacOS without problems.

2022-02-16 00:38 UTC, ravibhagavandas approved these changes

2022-02-16 09:43 UTC, aggarg approved these changes

2022-02-16 18:33 UTC, merged