Bump CBMC version to 5.95.1
FreeRTOS/corePKCS11 pull request #197
Opened 2024-06-06 09:51 UTC by tautschnig

Description
-----------
This will make proofs use the latest stable release of CBMC (and cbmc-viewer).

Test Steps
-----------
Tested in CI

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
n/a

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-06 12:24 UTC, shubnil approved these changes

2024-06-06 12:46 UTC, shubnil requested changes
Please fix the failing CBMC check

2024-06-07 12:59 UTC, tautschnig commented
I believe the attempt to verify C_CreateObject is now running out of memory. I'll bisect locally to see which CBMC change is causing this.

2024-10-01 07:27 UTC, tautschnig commented
Closing in favour of #200.

2024-10-01 07:27 UTC, closed without merging