Fix log formatting warnings when at DEBUG level
FreeRTOS/corePKCS11 pull request #43
Opened 2020-11-19 21:35 UTC by lundinc2

2020-11-19 21:50 UTC, alfred2g approved these changes

2020-11-19 22:09 UTC, n9wxu requested changes
Cast the variables in these log messages to pure C types.  i.e. %0lX goes with long int.
There are no guarantees that uint32_t goes with a %d or %x.  It depends upon the platform.  There ARE guarantees that int goes with %d or %x.

2020-11-20 00:39 UTC, n9wxu submitted a review, later dismissed

2020-11-20 01:09 UTC, alfred2g approved these changes

2020-11-20 19:12 UTC, n9wxu approved these changes

2020-11-20 19:15 UTC, merged